import { getUser } from "@/lib/supabase/supabaseActions";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Protected Route",
  description: "Generated by next-mods",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getUser();
  if (!user) redirect("/auth/signin");

  return <div>{children}</div>;
}